version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - "/app/node_modules"
      - "/app/.next"
